config/routes.rb
Rails.application.routes.draw do

  resources :articles
  resources :clickdatas

  root 'welcome#index'
  
  get 'welcome/index'
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/click_data.rb
class ClickData < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.all
	end

	def new
	end
	
	def create
		#render plain: params[:article].inspect
		@article = Article.new(article_params)
		@article.save
		redirect_to @article
	end

	def show
		@article = Article.find(params[:id])
	end

	private
		def article_params
			params.require(:article).permit(:title, :text)
		end
end

app/controllers/clickdatas_controller.rb
class ClickdatasController < ApplicationController
	def index
		@clickdatas = ClickData.all
	end

	def new
	end

	def create
		@clickdata = ClickData.new(clickdata_params)
		@clickdata.save
		render :json => @clickdata 
	end

	private
		def clickdata_params
			params.require(:clickdata).permit(:user_token, :x, :y, :scroll_position, :url)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/clickdatas_helper.rb
module ClickdatasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<h1>Listing articles</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

app/views/clickdatas/index.html.erb
<h1>Listing Click Datas <%= @clickdatas.length %> clicks </h1>
 
<table class="table table-bordered">
  <tr>
    <th>ID</th>
    <th>X</th>
    <th>Y</th>
    <th>User token</th>
    <th>Scroll position</th>
    <th>URL</th>
  </tr>
 
  <% @clickdatas.each do |clickdata| %>
    <tr>
      <td><%= clickdata.id %></td>
      <td><%= clickdata.x %></td>
      <td><%= clickdata.y %></td>
      <td><%= clickdata.user_token %></td>
      <td><%= clickdata.scroll_position %></td>
      <td><%= clickdata.url %></td>
    </tr>
  <% end %>
</table>

app/views/clickdatas/new.html.erb
<%= form_for :clickdata, url: clickdatas_path do |f| %>
  <p>
    <%= f.label :x %><br>
    <%= f.text_field :x %>
  </p>
 
  <p> 
    <%= f.label :y %><br>
    <%= f.text_field :y %>
  </p>

  <p>
    <%= f.label :user_token %><br>
    <%= f.text_field :user_token %>
  </p>

  <p>
    <%= f.label :scroll_position %><br>
    <%= f.text_field :scroll_position %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <title>Tcc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body onclick="save_click()">

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello Rails</h1>